In [26]:
url = 'https://www.bilibili.com/video/BV1Qp4y1n7EN?from=search&seid=16355075723330765190&spm_id_from=333.337.0.0'
response = requests.get(url)#get请求
if(response.status_code==200):
    
    soup = bs4.BeautifulSoup(response.text,'html.parser')
    print(soup.prettify())
    print(soup.find_all(id = 'list-box'))

<!DOCTYPE html>
<html>
 <head itemprop="video" itemscope="" itemtype="http://schema.org/VideoObject">
  <meta content="telephone=no, email=no" name="format-detection"/>
  <meta charset="utf-8" content="text/html" http-equiv="Content-Type"/>
  <meta content="333.788" name="spm_prefix"/>
  <meta content="no-referrer-when-downgrade" name="referrer"/>
  <script type="text/javascript">
   window.webAbTest={"webplayer":"6","play_continuously":"0","autoplay_optimize":"0","pc_player_autoplay_switch_reset":"1"}
  </script>
  <title data-vue-meta="true">
   尚硅谷大数据Hadoop 3.x（全新升级/部署+源码+实战）_哔哩哔哩_bilibili
  </title>
  <meta content="webkit" data-vue-meta="true" name="renderer"/>
  <meta content="IE=edge" data-vue-meta="true" http-equiv="X-UA-Compatible"/>
  <meta content="尚硅谷大数据Hadoop 3.x（全新升级/部署+源码+实战）,Hadoop3.1.3,hadoop3.x,大数据,hadoop,MapReduce,尚硅谷,HDFS,Yarn,科技,计算机技术,哔哩哔哩,Bilibili,B站,弹幕" data-vue-meta="true" itemprop="keywords" name="keywords"/>
Ja" data-vue-meta="true" itemprop="description" name

# 硬tm来,不要讲武德

In [24]:
import pandas as pd,numpy as np
import requests
import bs4

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

list_box = '''
<ul class="list-box"><li class="watched on"><a href="/video/BV1G4411c7N4?p=1" class="" title="001_尚硅谷_设计模式面试题(1)"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif"><span class="page-num">P1</span><span class="part">001_尚硅谷_设计模式面试题(1)</span></div><div class="duration">11:19</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=2" class="" title="002_尚硅谷_设计模式面试题(2)"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P2</span><span class="part">002_尚硅谷_设计模式面试题(2)</span></div><div class="duration">11:22</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=3" class="" title="003_尚硅谷_何时会用到设计模式"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P3</span><span class="part">003_尚硅谷_何时会用到设计模式</span></div><div class="duration">21:32</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=4" class="" title="004_尚硅谷_内容和授课方式"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P4</span><span class="part">004_尚硅谷_内容和授课方式</span></div><div class="duration">11:12</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=5" class="" title="005_尚硅谷_七大设计原则介绍"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P5</span><span class="part">005_尚硅谷_七大设计原则介绍</span></div><div class="duration">13:23</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=6" class="" title="006_尚硅谷_单一职责原则"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P6</span><span class="part">006_尚硅谷_单一职责原则</span></div><div class="duration">20:12</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=7" class="" title="007_尚硅谷_单一职责原则小结"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P7</span><span class="part">007_尚硅谷_单一职责原则小结</span></div><div class="duration">09:42</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=8" class="" title="008_尚硅谷_接口隔离原则(1)"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P8</span><span class="part">008_尚硅谷_接口隔离原则(1)</span></div><div class="duration">14:32</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=9" class="" title="009_尚硅谷_接口隔离原则(2)"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P9</span><span class="part">009_尚硅谷_接口隔离原则(2)</span></div><div class="duration">10:56</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=10" class="" title="010_尚硅谷_接口隔离原则小结"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P10</span><span class="part">010_尚硅谷_接口隔离原则小结</span></div><div class="duration">05:35</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=11" class="" title="011_尚硅谷_依赖倒转原则(1)"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P11</span><span class="part">011_尚硅谷_依赖倒转原则(1)</span></div><div class="duration">12:05</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=12" class="" title="012_尚硅谷_依赖倒转原则(2)"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P12</span><span class="part">012_尚硅谷_依赖倒转原则(2)</span></div><div class="duration">15:05</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=13" class="" title="013_尚硅谷_依赖倒转原则小结"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P13</span><span class="part">013_尚硅谷_依赖倒转原则小结</span></div><div class="duration">10:45</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=14" class="" title="014_尚硅谷_里氏替换原则(1)"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P14</span><span class="part">014_尚硅谷_里氏替换原则(1)</span></div><div class="duration">07:22</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=15" class="" title="015_尚硅谷_里氏替换原则(2)"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P15</span><span class="part">015_尚硅谷_里氏替换原则(2)</span></div><div class="duration">19:45</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=16" class="" title="016_尚硅谷_开闭原则(1)"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P16</span><span class="part">016_尚硅谷_开闭原则(1)</span></div><div class="duration">13:25</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=17" class="" title="017_尚硅谷_开闭原则(2)"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P17</span><span class="part">017_尚硅谷_开闭原则(2)</span></div><div class="duration">07:56</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=18" class="" title="018_尚硅谷_开闭原则小结"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P18</span><span class="part">018_尚硅谷_开闭原则小结</span></div><div class="duration">04:49</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=19" class="" title="019_尚硅谷_迪米特法则(1)"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P19</span><span class="part">019_尚硅谷_迪米特法则(1)</span></div><div class="duration">19:29</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=20" class="" title="020_尚硅谷_迪米特法则(2)"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P20</span><span class="part">020_尚硅谷_迪米特法则(2)</span></div><div class="duration">05:31</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=21" class="" title="021_尚硅谷_迪米特法则注意事项"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P21</span><span class="part">021_尚硅谷_迪米特法则注意事项</span></div><div class="duration">05:21</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=22" class="" title="022_尚硅谷_合成复用原则及小结"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P22</span><span class="part">022_尚硅谷_合成复用原则及小结</span></div><div class="duration">11:19</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=23" class="" title="023_尚硅谷_UML基本介绍"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P23</span><span class="part">023_尚硅谷_UML基本介绍</span></div><div class="duration">12:18</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=24" class="" title="024_尚硅谷_UML类图"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P24</span><span class="part">024_尚硅谷_UML类图</span></div><div class="duration">08:06</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=25" class="" title="025_尚硅谷_类的依赖、泛化和实现"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P25</span><span class="part">025_尚硅谷_类的依赖、泛化和实现</span></div><div class="duration">16:42</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=26" class="" title="026_尚硅谷_类的关联、聚合和组合"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P26</span><span class="part">026_尚硅谷_类的关联、聚合和组合</span></div><div class="duration">20:18</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=27" class="" title="027_尚硅谷_类图六大关系总结"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P27</span><span class="part">027_尚硅谷_类图六大关系总结</span></div><div class="duration">12:36</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=28" class="" title="028_尚硅谷_设计模式概述和分类"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P28</span><span class="part">028_尚硅谷_设计模式概述和分类</span></div><div class="duration">17:01</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=29" class="" title="029_尚硅谷_单例(静态常量饿汉式)"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P29</span><span class="part">029_尚硅谷_单例(静态常量饿汉式)</span></div><div class="duration">10:33</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=30" class="" title="030_尚硅谷_单例(静态代码块饿汉式)"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P30</span><span class="part">030_尚硅谷_单例(静态代码块饿汉式)</span></div><div class="duration">04:12</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=31" class="" title="031_尚硅谷_单例(线程不安全懒汉式)"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P31</span><span class="part">031_尚硅谷_单例(线程不安全懒汉式)</span></div><div class="duration">06:36</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=32" class="" title="032_尚硅谷_单例(线程安全懒汉式)"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P32</span><span class="part">032_尚硅谷_单例(线程安全懒汉式)</span></div><div class="duration">04:48</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=33" class="" title="033_尚硅谷_单例(同步代码块懒汉式)"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P33</span><span class="part">033_尚硅谷_单例(同步代码块懒汉式)</span></div><div class="duration">03:29</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=34" class="" title="034_尚硅谷_单例(DoubleCheck)"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P34</span><span class="part">034_尚硅谷_单例(DoubleCheck)</span></div><div class="duration">08:24</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=35" class="" title="035_尚硅谷_单例(静态内部类)"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P35</span><span class="part">035_尚硅谷_单例(静态内部类)</span></div><div class="duration">07:56</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=36" class="" title="036_尚硅谷_单例(枚举方式)"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P36</span><span class="part">036_尚硅谷_单例(枚举方式)</span></div><div class="duration">05:18</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=37" class="" title="037_尚硅谷_单例模式JKD源码分析"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P37</span><span class="part">037_尚硅谷_单例模式JKD源码分析</span></div><div class="duration">04:18</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=38" class="" title="038_尚硅谷_单例模式注意事项"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P38</span><span class="part">038_尚硅谷_单例模式注意事项</span></div><div class="duration">14:12</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=39" class="" title="039_尚硅谷_简单工厂模式(1)-披萨订购"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P39</span><span class="part">039_尚硅谷_简单工厂模式(1)-披萨订购</span></div><div class="duration">22:29</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=40" class="" title="040_尚硅谷_简单工厂模式(2)-披萨订购"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P40</span><span class="part">040_尚硅谷_简单工厂模式(2)-披萨订购</span></div><div class="duration">06:45</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=41" class="" title="041_尚硅谷_简单工厂模式(3)-披萨订购"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P41</span><span class="part">041_尚硅谷_简单工厂模式(3)-披萨订购</span></div><div class="duration">20:04</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=42" class="" title="042_尚硅谷_简单工厂模式(4)-披萨订购"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P42</span><span class="part">042_尚硅谷_简单工厂模式(4)-披萨订购</span></div><div class="duration">05:32</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=43" class="" title="043_尚硅谷_工厂方法模式(1)-披萨订购"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P43</span><span class="part">043_尚硅谷_工厂方法模式(1)-披萨订购</span></div><div class="duration">03:47</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=44" class="" title="044_尚硅谷_工厂方法模式(2)-披萨订购"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P44</span><span class="part">044_尚硅谷_工厂方法模式(2)-披萨订购</span></div><div class="duration">22:09</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=45" class="" title="045_尚硅谷_抽象工厂模式(1)-披萨订购"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P45</span><span class="part">045_尚硅谷_抽象工厂模式(1)-披萨订购</span></div><div class="duration">09:18</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=46" class="" title="046_尚硅谷_抽象工厂模式(2)-披萨订购"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P46</span><span class="part">046_尚硅谷_抽象工厂模式(2)-披萨订购</span></div><div class="duration">15:21</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=47" class="" title="047_尚硅谷_工厂模式-JDK源码分析"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P47</span><span class="part">047_尚硅谷_工厂模式-JDK源码分析</span></div><div class="duration">11:19</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=48" class="" title="048_尚硅谷_工厂模式-小结"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P48</span><span class="part">048_尚硅谷_工厂模式-小结</span></div><div class="duration">21:50</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=49" class="" title="049_尚硅谷_原型模式(1)-克隆羊"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P49</span><span class="part">049_尚硅谷_原型模式(1)-克隆羊</span></div><div class="duration">07:50</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=50" class="" title="050_尚硅谷_原型模式(2)-克隆羊"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P50</span><span class="part">050_尚硅谷_原型模式(2)-克隆羊</span></div><div class="duration">12:50</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=51" class="" title="051_尚硅谷_原型模式(3)-Spring源码分析"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P51</span><span class="part">051_尚硅谷_原型模式(3)-Spring源码分析</span></div><div class="duration">08:24</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=52" class="" title="052_尚硅谷_原型模式(4)-深拷贝"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P52</span><span class="part">052_尚硅谷_原型模式(4)-深拷贝</span></div><div class="duration">07:13</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=53" class="" title="053_尚硅谷_原型模式(5)-深拷贝"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P53</span><span class="part">053_尚硅谷_原型模式(5)-深拷贝</span></div><div class="duration">23:33</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=54" class="" title="054_尚硅谷_原型模式(6)-内容梳理"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P54</span><span class="part">054_尚硅谷_原型模式(6)-内容梳理</span></div><div class="duration">13:19</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=55" class="" title="055_尚硅谷_建造者模式(1)-盖房子"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P55</span><span class="part">055_尚硅谷_建造者模式(1)-盖房子</span></div><div class="duration">11:23</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=56" class="" title="056_尚硅谷_建造者模式(2)-原理类图"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P56</span><span class="part">056_尚硅谷_建造者模式(2)-原理类图</span></div><div class="duration">07:53</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=57" class="" title="057_尚硅谷_建造者模式(3)-盖房子"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P57</span><span class="part">057_尚硅谷_建造者模式(3)-盖房子</span></div><div class="duration">23:36</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=58" class="" title="058_尚硅谷_建造者模式(4)-StringBuilder源码"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P58</span><span class="part">058_尚硅谷_建造者模式(4)-StringBuilder源码</span></div><div class="duration">11:01</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=59" class="" title="059_尚硅谷_建造者模式(5)-内容梳理"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P59</span><span class="part">059_尚硅谷_建造者模式(5)-内容梳理</span></div><div class="duration">12:05</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=60" class="" title="060_尚硅谷_适配器模式-工作原理"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P60</span><span class="part">060_尚硅谷_适配器模式-工作原理</span></div><div class="duration">10:03</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=61" class="" title="061_尚硅谷_类适配器-电压问题"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P61</span><span class="part">061_尚硅谷_类适配器-电压问题</span></div><div class="duration">19:15</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=62" class="" title="062_尚硅谷_对象适配器-电压问题"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P62</span><span class="part">062_尚硅谷_对象适配器-电压问题</span></div><div class="duration">14:12</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=63" class="" title="063_尚硅谷_接口适配器-电压问题"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P63</span><span class="part">063_尚硅谷_接口适配器-电压问题</span></div><div class="duration">14:29</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=64" class="" title="064_尚硅谷_适配器模式-Dispatcher源码"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P64</span><span class="part">064_尚硅谷_适配器模式-Dispatcher源码</span></div><div class="duration">26:09</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=65" class="" title="065_尚硅谷_适配器模式-内容梳理"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P65</span><span class="part">065_尚硅谷_适配器模式-内容梳理</span></div><div class="duration">17:29</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=66" class="" title="066_尚硅谷_桥接模式(1)-手机问题"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P66</span><span class="part">066_尚硅谷_桥接模式(1)-手机问题</span></div><div class="duration">03:51</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=67" class="" title="067_尚硅谷_桥接模式(2)-原理类图"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P67</span><span class="part">067_尚硅谷_桥接模式(2)-原理类图</span></div><div class="duration">08:29</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=68" class="" title="068_尚硅谷_桥接模式(3)-手机问题"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P68</span><span class="part">068_尚硅谷_桥接模式(3)-手机问题</span></div><div class="duration">22:52</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=69" class="" title="069_尚硅谷_桥接模式(4)-JDBC源码"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P69</span><span class="part">069_尚硅谷_桥接模式(4)-JDBC源码</span></div><div class="duration">11:18</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=70" class="" title="070_尚硅谷_桥接模式(5)-内容梳理"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P70</span><span class="part">070_尚硅谷_桥接模式(5)-内容梳理</span></div><div class="duration">10:59</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=71" class="" title="071_尚硅谷_装饰者模式(1)-星巴克咖啡"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P71</span><span class="part">071_尚硅谷_装饰者模式(1)-星巴克咖啡</span></div><div class="duration">08:28</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=72" class="" title="072_尚硅谷_装饰者模式(2)-星巴克咖啡"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P72</span><span class="part">072_尚硅谷_装饰者模式(2)-星巴克咖啡</span></div><div class="duration">06:30</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=73" class="" title="073_尚硅谷_装饰者模式(3)-工作原理"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P73</span><span class="part">073_尚硅谷_装饰者模式(3)-工作原理</span></div><div class="duration">06:41</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=74" class="" title="074_尚硅谷_装饰者模式(4)-星巴克咖啡"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P74</span><span class="part">074_尚硅谷_装饰者模式(4)-星巴克咖啡</span></div><div class="duration">33:22</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=75" class="" title="075_尚硅谷_装饰者模式(5)-IO源码"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P75</span><span class="part">075_尚硅谷_装饰者模式(5)-IO源码</span></div><div class="duration">11:34</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=76" class="" title="076_尚硅谷_装饰者模式(6)-内容梳理"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P76</span><span class="part">076_尚硅谷_装饰者模式(6)-内容梳理</span></div><div class="duration">08:34</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=77" class="" title="077_尚硅谷_组合模式(1)-院校展示"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P77</span><span class="part">077_尚硅谷_组合模式(1)-院校展示</span></div><div class="duration">11:48</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=78" class="" title="078_尚硅谷_组合模式(2)-院校展示"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P78</span><span class="part">078_尚硅谷_组合模式(2)-院校展示</span></div><div class="duration">32:13</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=79" class="" title="079_尚硅谷_组合模式(3)-HashMap源码"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P79</span><span class="part">079_尚硅谷_组合模式(3)-HashMap源码</span></div><div class="duration">13:21</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=80" class="" title="080_尚硅谷_组合模式(4)-内容梳理"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P80</span><span class="part">080_尚硅谷_组合模式(4)-内容梳理</span></div><div class="duration">10:09</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=81" class="" title="081_尚硅谷_外观模式(1)-影院管理"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P81</span><span class="part">081_尚硅谷_外观模式(1)-影院管理</span></div><div class="duration">05:34</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=82" class="" title="082_尚硅谷_外观模式(2)-工作原理"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P82</span><span class="part">082_尚硅谷_外观模式(2)-工作原理</span></div><div class="duration">07:34</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=83" class="" title="083_尚硅谷_外观模式(3)-影院管理"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P83</span><span class="part">083_尚硅谷_外观模式(3)-影院管理</span></div><div class="duration">21:38</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=84" class="" title="084_尚硅谷_外观模式(4)-MyBatis源码"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P84</span><span class="part">084_尚硅谷_外观模式(4)-MyBatis源码</span></div><div class="duration">13:58</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=85" class="" title="085_尚硅谷_外观模式(5)-注意事项"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P85</span><span class="part">085_尚硅谷_外观模式(5)-注意事项</span></div><div class="duration">14:40</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=86" class="" title="086_尚硅谷_享元模式(1)-网站外包"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P86</span><span class="part">086_尚硅谷_享元模式(1)-网站外包</span></div><div class="duration">05:08</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=87" class="" title="087_尚硅谷_享元模式(2)-工作原理"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P87</span><span class="part">087_尚硅谷_享元模式(2)-工作原理</span></div><div class="duration">17:37</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=88" class="" title="088_尚硅谷_享元模式(3)-网站外包"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P88</span><span class="part">088_尚硅谷_享元模式(3)-网站外包</span></div><div class="duration">22:40</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=89" class="" title="089_尚硅谷_享元模式(4)-Integer源码"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P89</span><span class="part">089_尚硅谷_享元模式(4)-Integer源码</span></div><div class="duration">11:34</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=90" class="" title="090_尚硅谷_享元模式(5)-内容梳理"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P90</span><span class="part">090_尚硅谷_享元模式(5)-内容梳理</span></div><div class="duration">10:14</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=91" class="" title="091_尚硅谷_代理模式(1)-基本介绍"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P91</span><span class="part">091_尚硅谷_代理模式(1)-基本介绍</span></div><div class="duration">05:39</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=92" class="" title="092_尚硅谷_代理模式(2)-静态代理"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P92</span><span class="part">092_尚硅谷_代理模式(2)-静态代理</span></div><div class="duration">18:44</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=93" class="" title="093_尚硅谷_代理模式(3)-动态代理"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P93</span><span class="part">093_尚硅谷_代理模式(3)-动态代理</span></div><div class="duration">29:19</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=94" class="" title="094_尚硅谷_代理模式(4)-Cglib代理"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P94</span><span class="part">094_尚硅谷_代理模式(4)-Cglib代理</span></div><div class="duration">28:47</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=95" class="" title="095_尚硅谷_代理模式(5)-几种变体"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P95</span><span class="part">095_尚硅谷_代理模式(5)-几种变体</span></div><div class="duration">13:20</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=96" class="" title="096_尚硅谷_模板模式(1)-工作原理"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P96</span><span class="part">096_尚硅谷_模板模式(1)-工作原理</span></div><div class="duration">11:37</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=97" class="" title="097_尚硅谷_模板模式(2)-豆浆制作"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P97</span><span class="part">097_尚硅谷_模板模式(2)-豆浆制作</span></div><div class="duration">13:25</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=98" class="" title="098_尚硅谷_模板模式(3)-钩子方法"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P98</span><span class="part">098_尚硅谷_模板模式(3)-钩子方法</span></div><div class="duration">06:48</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=99" class="" title="099_尚硅谷_模板模式(4)-IOC源码"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P99</span><span class="part">099_尚硅谷_模板模式(4)-IOC源码</span></div><div class="duration">22:56</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=100" class="" title="100_尚硅谷_模板模式(5)-细节说明"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P100</span><span class="part">100_尚硅谷_模板模式(5)-细节说明</span></div><div class="duration">11:20</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=101" class="" title="101_尚硅谷_命令模式(1)-工作原理"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P101</span><span class="part">101_尚硅谷_命令模式(1)-工作原理</span></div><div class="duration">15:26</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=102" class="" title="102_尚硅谷_命令模式(2)-遥控器"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P102</span><span class="part">102_尚硅谷_命令模式(2)-遥控器</span></div><div class="duration">19:29</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=103" class="" title="103_尚硅谷_命令模式(3)-遥控器"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P103</span><span class="part">103_尚硅谷_命令模式(3)-遥控器</span></div><div class="duration">23:58</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=104" class="" title="104_尚硅谷_命令模式(4)-JdbcTml源码"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P104</span><span class="part">104_尚硅谷_命令模式(4)-JdbcTml源码</span></div><div class="duration">16:13</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=105" class="" title="105_尚硅谷_命令模式(5)-内容梳理"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P105</span><span class="part">105_尚硅谷_命令模式(5)-内容梳理</span></div><div class="duration">09:53</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=106" class="" title="106_尚硅谷_访问者模式(1)-歌手评分"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P106</span><span class="part">106_尚硅谷_访问者模式(1)-歌手评分</span></div><div class="duration">04:01</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=107" class="" title="107_尚硅谷_访问者模式(2)-原理类图"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P107</span><span class="part">107_尚硅谷_访问者模式(2)-原理类图</span></div><div class="duration">13:35</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=108" class="" title="108_尚硅谷_访问者模式(3)-歌手评分"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P108</span><span class="part">108_尚硅谷_访问者模式(3)-歌手评分</span></div><div class="duration">25:10</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=109" class="" title="109_尚硅谷_访问者模式(4)-双分派"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P109</span><span class="part">109_尚硅谷_访问者模式(4)-双分派</span></div><div class="duration">06:55</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=110" class="" title="110_尚硅谷_访问者模式(5)-使用细节"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P110</span><span class="part">110_尚硅谷_访问者模式(5)-使用细节</span></div><div class="duration">08:15</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=111" class="" title="111_尚硅谷_迭代器模式(1)-统一遍历问题"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P111</span><span class="part">111_尚硅谷_迭代器模式(1)-统一遍历问题</span></div><div class="duration">04:15</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=112" class="" title="112_尚硅谷_迭代器模式(2)-原理类图"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P112</span><span class="part">112_尚硅谷_迭代器模式(2)-原理类图</span></div><div class="duration">15:50</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=113" class="" title="113_尚硅谷_迭代器模式(3)-统一遍历问题"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P113</span><span class="part">113_尚硅谷_迭代器模式(3)-统一遍历问题</span></div><div class="duration">07:07</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=114" class="" title="114_尚硅谷_迭代器模式(4)-统一遍历问题"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P114</span><span class="part">114_尚硅谷_迭代器模式(4)-统一遍历问题</span></div><div class="duration">34:42</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=115" class="" title="115_尚硅谷_迭代器模式(5)-JDK源码"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P115</span><span class="part">115_尚硅谷_迭代器模式(5)-JDK源码</span></div><div class="duration">19:24</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=116" class="" title="116_尚硅谷_迭代器模式(6)-使用细节"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P116</span><span class="part">116_尚硅谷_迭代器模式(6)-使用细节</span></div><div class="duration">11:42</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=117" class="" title="117_尚硅谷_观察者模式(1)-天气预报"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P117</span><span class="part">117_尚硅谷_观察者模式(1)-天气预报</span></div><div class="duration">07:21</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=118" class="" title="118_尚硅谷_观察者模式(2)-天气预报"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P118</span><span class="part">118_尚硅谷_观察者模式(2)-天气预报</span></div><div class="duration">13:24</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=119" class="" title="119_尚硅谷_观察者模式(3)-工作原理"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P119</span><span class="part">119_尚硅谷_观察者模式(3)-工作原理</span></div><div class="duration">04:10</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=120" class="" title="120_尚硅谷_观察者模式(4)-天气预报"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P120</span><span class="part">120_尚硅谷_观察者模式(4)-天气预报</span></div><div class="duration">24:26</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=121" class="" title="121_尚硅谷_观察者模式(5)-Observable源码"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P121</span><span class="part">121_尚硅谷_观察者模式(5)-Observable源码</span></div><div class="duration">06:55</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=122" class="" title="122_尚硅谷_观察者模式(6)-内容梳理"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P122</span><span class="part">122_尚硅谷_观察者模式(6)-内容梳理</span></div><div class="duration">07:03</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=123" class="" title="123_尚硅谷_中介者模式(1)-智能家庭"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P123</span><span class="part">123_尚硅谷_中介者模式(1)-智能家庭</span></div><div class="duration">09:57</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=124" class="" title="124_尚硅谷_中介者模式(2)-工作原理"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P124</span><span class="part">124_尚硅谷_中介者模式(2)-工作原理</span></div><div class="duration">16:21</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=125" class="" title="125_尚硅谷_中介者模式(3)-智能家庭"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P125</span><span class="part">125_尚硅谷_中介者模式(3)-智能家庭</span></div><div class="duration">26:25</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=126" class="" title="126_尚硅谷_中介者模式(4)-内容梳理"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P126</span><span class="part">126_尚硅谷_中介者模式(4)-内容梳理</span></div><div class="duration">06:55</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=127" class="" title="127_尚硅谷_备忘录模式(1)-游戏角色"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P127</span><span class="part">127_尚硅谷_备忘录模式(1)-游戏角色</span></div><div class="duration">02:52</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=128" class="" title="128_尚硅谷_备忘录模式(2)-工作原理"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P128</span><span class="part">128_尚硅谷_备忘录模式(2)-工作原理</span></div><div class="duration">25:29</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=129" class="" title="129_尚硅谷_备忘录模式(3)-游戏角色"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P129</span><span class="part">129_尚硅谷_备忘录模式(3)-游戏角色</span></div><div class="duration">16:22</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=130" class="" title="130_尚硅谷_备忘录模式(4)-注意事项"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P130</span><span class="part">130_尚硅谷_备忘录模式(4)-注意事项</span></div><div class="duration">08:20</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=131" class="" title="131_尚硅谷_解释器模式(1)-计算式求值"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P131</span><span class="part">131_尚硅谷_解释器模式(1)-计算式求值</span></div><div class="duration">03:16</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=132" class="" title="132_尚硅谷_解释器模式(2)-原理类图"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P132</span><span class="part">132_尚硅谷_解释器模式(2)-原理类图</span></div><div class="duration">13:18</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=133" class="" title="133_尚硅谷_解释器模式(3)-计算式求值"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P133</span><span class="part">133_尚硅谷_解释器模式(3)-计算式求值</span></div><div class="duration">37:56</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=134" class="" title="134_尚硅谷_解释器模式(4)-SpelExp源码"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P134</span><span class="part">134_尚硅谷_解释器模式(4)-SpelExp源码</span></div><div class="duration">16:44</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=135" class="" title="135_尚硅谷_解释器模式(5)-总结"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P135</span><span class="part">135_尚硅谷_解释器模式(5)-总结</span></div><div class="duration">08:45</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=136" class="" title="136_尚硅谷_状态模式(1)-工作原理图"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P136</span><span class="part">136_尚硅谷_状态模式(1)-工作原理图</span></div><div class="duration">11:19</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=137" class="" title="137_尚硅谷_状态模式(2)-抽奖活动"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P137</span><span class="part">137_尚硅谷_状态模式(2)-抽奖活动</span></div><div class="duration">33:57</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=138" class="" title="138_尚硅谷_状态模式(3)-借贷平台源码"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P138</span><span class="part">138_尚硅谷_状态模式(3)-借贷平台源码</span></div><div class="duration">18:56</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=139" class="" title="139_尚硅谷_状态模式(4)-注意事项"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P139</span><span class="part">139_尚硅谷_状态模式(4)-注意事项</span></div><div class="duration">09:12</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=140" class="" title="140_尚硅谷_策略模式(1)-鸭子问题"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P140</span><span class="part">140_尚硅谷_策略模式(1)-鸭子问题</span></div><div class="duration">12:51</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=141" class="" title="141_尚硅谷_策略模式(2)-工作原理"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P141</span><span class="part">141_尚硅谷_策略模式(2)-工作原理</span></div><div class="duration">09:09</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=142" class="" title="142_尚硅谷_策略模式(3)-鸭子问题"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P142</span><span class="part">142_尚硅谷_策略模式(3)-鸭子问题</span></div><div class="duration">22:51</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=143" class="" title="143_尚硅谷_策略模式(4)-Arrays源码"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P143</span><span class="part">143_尚硅谷_策略模式(4)-Arrays源码</span></div><div class="duration">09:48</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=144" class="" title="144_尚硅谷_策略模式(5)-内容梳理"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P144</span><span class="part">144_尚硅谷_策略模式(5)-内容梳理</span></div><div class="duration">09:39</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=145" class="" title="145_尚硅谷_职责链模式(1)-采购审批"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P145</span><span class="part">145_尚硅谷_职责链模式(1)-采购审批</span></div><div class="duration">05:43</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=146" class="" title="146_尚硅谷_职责链模式(2)-工作原理"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P146</span><span class="part">146_尚硅谷_职责链模式(2)-工作原理</span></div><div class="duration">10:38</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=147" class="" title="147_尚硅谷_职责链模式(3)-采购审批"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P147</span><span class="part">147_尚硅谷_职责链模式(3)-采购审批</span></div><div class="duration">23:56</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=148" class="" title="148_尚硅谷_职责链模式(4)-SpringMVC源码"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P148</span><span class="part">148_尚硅谷_职责链模式(4)-SpringMVC源码</span></div><div class="duration">17:25</div></div></a></li><li class=""><a href="/video/BV1G4411c7N4?p=149" class="" title="149_尚硅谷_职责链模式(5)-内容梳理"><div class="clickitem"><div class="link-content"><img src="//s1.hdslb.com/bfs/static/jinkela/video/asserts/playing.gif" style="display: none;"><span class="page-num">P149</span><span class="part">149_尚硅谷_职责链模式(5)-内容梳理</span></div><div class="duration">08:39</div></div></a></li></ul>
'''
soup = bs4.BeautifulSoup(list_box,'lxml')
# print(soup.prettify())

arr_table = []
for i,j in zip(soup.find_all(class_ = 'part'),soup.find_all(class_ = 'duration')):
    arr = [i.text,j.text]
    arr_table.append(arr)
df = pd.DataFrame(np.array(arr_table), columns=['题目','时长'])
df.to_excel(r'E:\文件储存\OneDrive - Newcastle University\尚硅谷Java设计模式.xlsx')

In [2]:
type(True+False)

int

In [8]:
import numpy as np
type(round(np.pi,0))

float

In [15]:
phi = (1+np.sqrt(5))/2
phi

1.618033988749895

In [16]:
psi = 1+1/phi
psi

1.618033988749895

In [35]:
for i in range(0,5):
    print(i)

0
1
2
3
4


In [30]:
n = np.arange(1,101)
n

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [33]:
t = n*(n+1)*(n+2)/6

array([1.00000e+00, 4.00000e+00, 1.00000e+01, 2.00000e+01, 3.50000e+01,
       5.60000e+01, 8.40000e+01, 1.20000e+02, 1.65000e+02, 2.20000e+02,
       2.86000e+02, 3.64000e+02, 4.55000e+02, 5.60000e+02, 6.80000e+02,
       8.16000e+02, 9.69000e+02, 1.14000e+03, 1.33000e+03, 1.54000e+03,
       1.77100e+03, 2.02400e+03, 2.30000e+03, 2.60000e+03, 2.92500e+03,
       3.27600e+03, 3.65400e+03, 4.06000e+03, 4.49500e+03, 4.96000e+03,
       5.45600e+03, 5.98400e+03, 6.54500e+03, 7.14000e+03, 7.77000e+03,
       8.43600e+03, 9.13900e+03, 9.88000e+03, 1.06600e+04, 1.14800e+04,
       1.23410e+04, 1.32440e+04, 1.41900e+04, 1.51800e+04, 1.62150e+04,
       1.72960e+04, 1.84240e+04, 1.96000e+04, 2.08250e+04, 2.21000e+04,
       2.34260e+04, 2.48040e+04, 2.62350e+04, 2.77200e+04, 2.92600e+04,
       3.08560e+04, 3.25090e+04, 3.42200e+04, 3.59900e+04, 3.78200e+04,
       3.97110e+04, 4.16640e+04, 4.36800e+04, 4.57600e+04, 4.79050e+04,
       5.01160e+04, 5.23940e+04, 5.47400e+04, 5.71550e+04, 5.964

In [39]:
u = []
i = 15
while(i>=-39):
    u.append(i)
    i -= 6

[15, 9, 3, -3, -9, -15, -21, -27, -33, -39]

In [4]:
type(True-1)

int

In [6]:
type(str(0.0))

str

In [7]:
type("False")

str

In [56]:
x = np.random.randint(-10,10,size=100)
x

array([  5,  -2,  -5,   5,   3,  -5,  -7,  -4,   8,   1,   7,   3,   8,
         3,  -3,  -4,   3,   2,   4,   1,  -8,   2,  -4,  -2,  -8,  -9,
         9,   5,   3,   9,   2,  -9,   8,  -8,   6,  -6,  -6,   4,   1,
        -2, -10, -10,  -1,   9,  -6,  -6,  -4,  -6,  -3,  -6,   7,  -1,
         0,  -3,   8,  -7,   6,   1,   9,   0,  -5,   3,  -5,   3,   1,
        -5,   9,   4,   4,   9,   1,  -3,  -9,  -1,   4,  -8,  -4,   6,
        -9,   5,   0,  -7,  -5,  -9,  -2,  -5,  -2,  -9,  -1,   8,   2,
         7, -10,  -8,  -8,   9,   0,  -4,  -2,   0])

In [59]:
x[12]

8

In [60]:
x[12] = 0
x

array([  5,  -2,  -5,   5,   3,  -5,  -7,  -4,   8,   1,   7,   3,   0,
         3,  -3,  -4,   3,   2,   4,   1,  -8,   2,  -4,  -2,  -8,  -9,
         9,   5,   3,   9,   2,  -9,   8,  -8,   6,  -6,  -6,   4,   1,
        -2, -10, -10,  -1,   9,  -6,  -6,  -4,  -6,  -3,  -6,   7,  -1,
         0,  -3,   8,  -7,   6,   1,   9,   0,  -5,   3,  -5,   3,   1,
        -5,   9,   4,   4,   9,   1,  -3,  -9,  -1,   4,  -8,  -4,   6,
        -9,   5,   0,  -7,  -5,  -9,  -2,  -5,  -2,  -9,  -1,   8,   2,
         7, -10,  -8,  -8,   9,   0,  -4,  -2,   0])

In [76]:
## d
np.sort(x)
x

array([-10, -10, -10,  -9,  -9,  -9,  -9,  -9,  -9,  -8,  -8,  -8,  -8,
        -8,  -8,  -7,  -7,  -7,  -6,  -6,  -6,  -6,  -6,  -6,  -5,  -5,
        -5,  -5,  -5,  -5,  -5,  -4,  -4,  -4,  -4,  -4,  -4,  -3,  -3,
        -3,  -3,  -2,  -2,  -2,  -2,  -2,  -2,  -1,  -1,  -1,  -1,   0,
         0,   0,   0,   0,   0,   1,   1,   1,   1,   1,   1,   2,   2,
         2,   2,   3,   3,   3,   3,   3,   3,   3,   4,   4,   4,   4,
         4,   5,   5,   5,   5,   6,   6,   6,   7,   7,   7,   8,   8,
         8,   8,   9,   9,   9,   9,   9,   9,   9])

In [75]:
## e
x = -(np.sort(-x))
x

TypeError: bad operand type for unary -: 'NoneType'

In [62]:
## f
y = x[x<=0]


NameError: name 'X' is not defined

In [67]:
A = np.random.rand(10,20)
A

array([[0.58974034, 0.08259359, 0.43172051, 0.33431618, 0.08559829,
        0.75762351, 0.70743101, 0.24417774, 0.7692421 , 0.65076637,
        0.28309497, 0.35847885, 0.84783898, 0.622744  , 0.43925358,
        0.74097233, 0.63175975, 0.29086492, 0.32611239, 0.36197879],
       [0.08563888, 0.73216232, 0.92148727, 0.04100659, 0.74257914,
        0.1086162 , 0.22093009, 0.83041452, 0.52624813, 0.02300048,
        0.79796241, 0.23534735, 0.10860545, 0.53545738, 0.95428508,
        0.4369586 , 0.63916098, 0.552656  , 0.24565524, 0.49659716],
       [0.08369149, 0.52266284, 0.31527815, 0.6100275 , 0.17946384,
        0.36810584, 0.30071948, 0.74962803, 0.70993038, 0.59512575,
        0.97537271, 0.45483934, 0.69281486, 0.7121889 , 0.90050864,
        0.98875852, 0.52289269, 0.42406356, 0.70543652, 0.17182266],
       [0.73703583, 0.6161288 , 0.3221316 , 0.31807436, 0.76893432,
        0.61473248, 0.5837809 , 0.59168106, 0.90115829, 0.55103281,
        0.30494372, 0.57720699, 0.91000903, 0

In [69]:
A[6][8]

0.6744496397121338

In [73]:
for i in A[5]:
    print(i)

0.3859540004775196
0.43222395469790975
0.6068372466117288
0.28579577932209754
0.8939950676373768
0.3772963615896163
0.8486368300740252
0.3422093100315384
0.5383512714429132
0.3782956742151722
0.12431417800589806
0.48147698953057994
0.2812930117313277
0.017161937644476044
0.01626564316843171
0.029988712953309404
0.11979675699020653
0.6418668218285234
0.7689956645835196
0.9137725114773885


In [263]:
x=1
y=2
if(x==y):
    z = 0
elif(x>y):
    z = 1
else:
    z = -1
z

-1

In [77]:
x=4
y=12
while(y-x>1):
    y = (x+y)/2
    print(y)

8.0
6.0
5.0


In [86]:
C = np.zeros(60)
C

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [89]:
A = np.random.randint(-10,10,size=60)
B = np.random.randint(-10,10,size=60)

k = 0
for i,j in zip(A,B):
    if i>=j:
        C[k] = i
    else:
        C[k] = j
    k += 1
C

array([ -1.,   5.,   2.,   5.,   7.,   1.,   5.,   2.,   1.,   6.,   2.,
         8.,   9.,   9.,   5.,   9.,   1.,   7.,   3.,   7.,  -1.,   7.,
         6.,   7.,   4.,   1.,   7.,  -4.,   7.,   3.,   0.,   0.,   5.,
         7.,   8.,   2.,   8.,   9.,   4.,   6.,   6.,   8.,   0.,   9.,
         8.,   1.,   7.,   9.,   7.,   6.,  -6.,  -6.,   2.,   1.,   7.,
        -4.,   2.,   9.,   8., -10.])

In [113]:
np.random.randint(1,7)

2

In [175]:
def dice_roll():
    a = np.random.randint(1,7)
    b = np.random.randint(1,7)
    return a,b

# dice_roll()

In [183]:
def dice_rolln(x):
    lst = []
    for i in range(int(x)):
        lst.append(np.random.randint(1,7))
    return lst

dice_rolln(6)

[5, 4, 3, 6, 4, 4]

In [260]:
x = np.array([[a, b, c]])
y = np.array([[a, b, c]])

x=0
np.append(x, y, axis=0)

ValueError: zero-dimensional arrays cannot be concatenated

In [262]:
x=0
for i in range(6):
    a = np.random.randint(1,7)
    b = np.random.randint(1,7)
    c = np.random.randint(1,7)
    
    result = np.array([[a, b, c]])
    
    try: 
        x = np.concatenate((x, result), axis=0)
    except:
        x = result

print(x)
    


[[3 3 2]
 [6 5 5]
 [6 2 4]
 [1 6 6]
 [5 1 4]
 [2 2 3]]


In [249]:
def f0n_inter(n):
    if n % 2==0:
        return n / 2
    else:
        return (3*n+1)/2

fn_inter(5)

8.0