In [4]:
#全部行都能输出
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import numpy as np

print(np.__version__)

1.16.2


## 创建一个长度为10的空向量 (★☆☆) 
(**提示**: ```np.zeros```)

In [5]:
np.zeros((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

##  创建一个长度为10并且除了第五个值为1的空向量 (★☆☆) 
(**提示**: ```array[4]```)

In [8]:
array =np.zeros((10))
array[4] =1
array

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

## 创建一个值域范围从10到49的向量(★☆☆) 
(**提示**: ```np.arange```)

In [11]:
np.linspace(10,49,num=39,dtype="int32")

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 49])

##  反转一个向量(第一个元素变为最后一个) (★☆☆) 
(**提示**: ```array[::-1]```)

In [13]:
Z = np.arange(50)
Z = -np.sort(-Z)
Z

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

##  创建一个 ```3x3``` 并且值从0到8的矩阵(★☆☆) 
(**提示**: ```reshape```)

In [8]:
a = np.array(range(9))
a
a.reshape((3,3))

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 找到数组```[1,2,0,0,4,0]```中非0元素的位置索引 (★☆☆) 
(**提示**: ```np.nonzero```)

In [35]:
a=[1,2,0,0,4,0]
np.nonzero(a)[0]

array([0, 1, 4], dtype=int64)

## 创建一个 ```3x3``` 的单位矩阵 (★☆☆) 
(**提示**: ```np.eye```)

In [10]:
np.eye(3,dtype="int32")

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## 创建一个 ```3x3x3```的随机数组 (★☆☆) 
(**提示**: ```np.random.random```)

In [13]:
np.random.random((3,3,3))

array([[[0.19427538, 0.67865802, 0.81341877],
        [0.32494198, 0.14593251, 0.01301822],
        [0.01099237, 0.57608415, 0.94566864]],

       [[0.75190762, 0.3429324 , 0.83460635],
        [0.8888031 , 0.30727232, 0.70937647],
        [0.94517423, 0.09533518, 0.63422041]],

       [[0.42670644, 0.00105663, 0.02608457],
        [0.74296511, 0.72141176, 0.10962849],
        [0.89767554, 0.07485025, 0.75247868]]])

## 创建一个 ```10x10``` 的随机数组并找到它的最大值和最小值 (★☆☆) 
(**提示**: ```min, max```)

In [16]:
a = np.random.random((10,10))
a.min()
a.max()

0.0028744987127590216

0.9951924879608168

## 创建一个长度为30的随机向量并找到它的平均值 (★☆☆) 
(**提示**: ```mean```)

In [18]:
a = np.random.random(30)
a.mean()

0.45403593585285207

## 创建一个二维数组，其中边界值为1，其余值为0 (★☆☆) 
(**提示**: ```array[1:-1, 1:-1]```)

In [66]:
a = np.ones((10,10),dtype="int32")
a[1:9,1:9]=0
a

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

## 创建一个 ```5x5```的矩阵，并设置值1,2,3,4落在其对角线下方位置 (★☆☆) 
(**提示**: ```np.diag```)

In [20]:
b = np.zeros((5,5))
a=list(range(1,6))
np.diag(a,-1)

array([[0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0]])

## 一个```5x3```的矩阵与一个```3x2```的矩阵相乘，实矩阵乘积是什么？ (★☆☆) 
(**提示**: ```np.dot```)

In [23]:
a= np.ones((5,3),dtype="int32")
b=np.ones((3,2),dtype="int32")
a.dot(b)

array([[3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3]])

## 给定一个一维数组，对其在3到8之间的所有元素取反 (★☆☆) 
(**提示**: ```>, <=```)

In [73]:
a = np.arange(11)
a[a>3 &a<=8] *= -1
a


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

## 如何找到两个数组中的共同元素? (★☆☆) 
(**提示**: ```np.intersect1d```)

In [77]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
np.intersect1d(Z1,Z2)

array([2, 4, 6, 9])

## 用提取一个随机数组的整数部分(★★☆) 
(**提示**: ```%, np.floor, np.ceil, astype, np.trunc```)

In [92]:
np.random.seed(20)
z = np.random.uniform(0,10,10)   #从均匀分布中抽取样本,区间左闭右开
z

array([5.88130801, 8.97713728, 8.91530729, 8.15837477, 0.35889586,
       6.91757582, 3.78680942, 5.18510945, 6.57951466, 1.93850218])

In [85]:
z-z%1

array([5., 8., 8., 8., 0., 6., 3., 5., 6., 1.])

In [86]:
z.astype(int)

array([5, 8, 8, 8, 0, 6, 3, 5, 6, 1])

In [91]:
np.ceil(z)-1
np.floor(z)

array([5., 8., 8., 8., 0., 6., 3., 5., 6., 1.])

array([5., 8., 8., 8., 0., 6., 3., 5., 6., 1.])

In [93]:
np.trunc(z)

array([5., 8., 8., 8., 0., 6., 3., 5., 6., 1.])

##  创建一个```5x5```的矩阵，其中每行的数值范围从0到4 (★★☆) 
(**提示**: ```np.arange```)

In [46]:
np.arange(5)*np.ones((5,5),dtype="int32")

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

##  创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1 (★★☆) 
(**提示**: ```np.linspace```)

In [71]:
np.linspace(0,1,num=10,endpoint=False)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

## 创建一个长度为10的随机向量，并将其升序排序 (★★☆) 
(**提示**: ```sort```)

In [55]:
a = np.empty((1,10))
a.sort()
a

array([[0.05323742, 0.23461129, 0.2746152 , 0.35659292, 0.38518794,
        0.53984742, 0.69637341, 0.74642538, 0.85921161, 0.99438665]])

## 对于两个随机数组A和B，检查它们是否相等(★★☆) 
(**提示**: ``` np.array_equal```)

In [94]:
np.random.randint(1)==np.random.random(1)

array([False])

## 创建一个长度为10的向量，并将向量中最大值替换为1 (★★☆) 
(**提示**: ```argmax```)

In [118]:
np.random.seed(10)
Z = np.random.randint(1,20,10)
Z
Z[Z.argmax()]=1
Z

array([10,  5, 16,  1, 18, 17, 18,  9, 10,  1])

array([10,  5, 16,  1,  1, 17, 18,  9, 10,  1])

## 如何将32位的浮点数(```float```)数组转换为对应的整数(```integer```)?
(**提示**: ```astype()```)

In [97]:
Z = np.arange(10, dtype=np.float32)
Z.astype("int32")


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 对于```numpy```数组，```enumerate```的等价操作是什么？(★★☆) 
(**提示**: ```np.ndenumerate```)

In [148]:
Z = np.arange(9).reshape(3,3)
Z
tuple(np.ndenumerate(Z))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

(((0, 0), 0),
 ((0, 1), 1),
 ((0, 2), 2),
 ((1, 0), 3),
 ((1, 1), 4),
 ((1, 2), 5),
 ((2, 0), 6),
 ((2, 1), 7),
 ((2, 2), 8))

## 一个二维数组如何每一行的值都减去每一行的平均值，生成新的一个数组(★★☆) 
(**提示**: ```mean(axis=,keepdims=True)```)

In [149]:
np.random.seed(10)
X = np.random.randint(1, 10,(10,2))
X
X1 = np.mean(X,axis=1,keepdims=True)
X1

X2=X-X1
X2

array([[5, 1],
       [2, 1],
       [2, 9],
       [1, 9],
       [7, 5],
       [4, 1],
       [5, 7],
       [9, 2],
       [9, 5],
       [2, 4]])

array([[3. ],
       [1.5],
       [5.5],
       [5. ],
       [6. ],
       [2.5],
       [6. ],
       [5.5],
       [7. ],
       [3. ]])

array([[ 2. , -2. ],
       [ 0.5, -0.5],
       [-3.5,  3.5],
       [-4. ,  4. ],
       [ 1. , -1. ],
       [ 1.5, -1.5],
       [-1. ,  1. ],
       [ 3.5, -3.5],
       [ 2. , -2. ],
       [-1. ,  1. ]])

##  如何取出一个方阵的的对角线? (★★★) 
(**提示**: ```np.diag```)

In [123]:
import numpy as np
A=np.random.randint(1,10,(3,3))
A
np.diag(A)


array([[5, 8, 9],
       [9, 3, 7],
       [3, 9, 9]])

array([5, 3, 9])

## 如何对一个数组中任意两行做交换? (★★★) 
(**提示**: ```array[[]] = array[[]]```)

In [3]:
A = np.arange(25).reshape(5,5)
A
np.random.seed(1)
a= np.random.randint(0,4,1)
a
A[a+1:a:-1]

TypeError: only integer scalar arrays can be converted to a scalar index

## 如何找到一个数组中出现频率最高的值？ 
(**提示**: ```np.bincount, argmax```)

In [7]:
np.random.seed(20)
Z = np.random.randint(5,10,50)
Z
np.bincount(Z)
np.argmax(np.bincount(Z))

array([8, 7, 9, 7, 6, 9, 8, 7, 5, 5, 7, 7, 8, 8, 5, 5, 6, 7, 7, 8, 7, 6,
       8, 7, 8, 8, 6, 5, 7, 8, 8, 7, 8, 6, 5, 8, 5, 7, 7, 8, 8, 5, 7, 6,
       7, 8, 7, 6, 9, 9])

array([ 0,  0,  0,  0,  0,  8,  7, 16, 15,  4], dtype=int64)

7

## 如何找到一个数组的第n个最大值? (★★★) 
(**提示**: ```np.argsort```)

In [9]:
a=np.random.randint(1,100,10)
a
np.argsort(a)
np.argsort(a)[9]

array([86, 18, 41, 83, 43, 61, 85, 31, 37,  9])

array([9, 1, 7, 8, 2, 4, 5, 3, 6, 0], dtype=int64)

0

10